### ISSUE TITLE
Does this work with 5.1 ?

### ISSUE THREAD

**Issue by CiscoKidxx** [hcabel/UnrealVsCodeHelper#3]
I have an empty panel in my UE5.1 project. The .cpp -> .h switch feature is working nicely. The Toolbar and doc search are not. Thanks for your plugin! I am excited to use it. If there is more information I can provide please let me know.

UE: 5.1.0

Vs Code:
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

![image](https://user-images.githubusercontent.com/12367476/211997434-1c94efb7-f9a0-4f54-b99f-d7bd07133dba.png)

**Comment by hcabel** [comment]
Hello,

I've just check, and this is happening to me too. (I'm currently doing web so I haven't check for a while 😄)
I'll be fixing this when I have some time.

Thanks for your time.

**Comment by CiscoKidxx** [comment]
@hcabel thanks for the reply!

**Comment by hcabel** [comment]
Hello @CiscoKidxx,

I've just fixed the issue in the new version (`1.1.1`).
Something about the content policy may have change, the way I was loading my script were violated this policy and because of that they were blocked.

Anyway hope it work fine for you now. (it should)

Have a nice day.
