### ISSUE TITLE
UVCH BROWSER Unable to access

### ISSUE THREAD

**Issue by hideoutbush** [hcabel/UnrealVsCodeHelper#6]
hello,I'm try to use ctrl+F1 key operation visit the Unreal official documentation,but Plugins gave me a mistake,As shown in the following picture
![微信截图_20231221140251](https://github.com/hcabel/UnrealVsCodeHelper/assets/93957385/074f7395-2736-4940-b736-793647d69511)

**Comment by hcabel** [comment]
Thanks for reporting, I'll close it for being a duplicate of [issue5](https://github.com/hcabel/UnrealVsCodeHelper/issues/5) and fix it soon
